version: '3.3'

services:
  front:
      image: node:10.17
      networks:
        - application
      ports: 
        - "3000:3000"
      volumes:
        - "./front:/var/www"
      working_dir: /var/www
      command: npm run install-start
networks: 
  application: 
    driver: bridge